backend:
  name: github
  repo: mwood23/pride-of-the-meadows

media_folder: static/assets
public_folder: /assets

collections:
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title}
      - { name: data, label: Created At, widget: date }
      - { name: body, label: Post, widget: markdown }
      - { name: theProblem, label: Problem, widget: markdown }
      - { name: theSolution, label: Solution, widget: markdown }
      - { name: anotherHtmlBlock, label: HtmlBlock, widget: markdown }
      - { name: powerStatement, label Power Statement, widget: string}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - label: "City"
        name: "airport-code"
        widget: "select"
        options:
          - { label: "Chicago", value: "ORD" }
          - { label: "Paris", value: "CDG" }
          - { label: "Tokyo", value: "HND" }
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
      - {label: "Description", name: "description", widget: "text"}
      - label: "Puppy Count"
        name: "puppies"
        widget: "number"
        default: 2
        valueType: "int"
    min: 1
    max: 101
  - name: recipe
    label: Recipes
    folder: src/recipes
    create: true
    fields:
      - { name: title, label: Title}
      - { name: data, label: Created At, widget: date }
      - { name: body, label: Post, widget: markdown }
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Settings"
        file: "src/settings.yml"
        description: "General Site Settings"
        fields:
          - {label: "Global title", name: "site_title", widget: "string"}
          - label: "Post Settings"
            name: posts
            widget: "object"
            fields:
              - {label: "Number of posts on frontpage", name: front_limit, widget: number}
              - {label: "Default Author", name: site_author, widget: string}
  - name: "pages"
    label: "Pages"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "home"
        label: "Home"
        file: "src/pages/page-content/home.yml"
        description: "Home page content"
        fields:
          - {label: "Intro blurb", name: "intro_blurb", widget: "string"}
          - label: "About Us Icon Blurb Row"
            name: about_us_icon_blurb_row
            widget: "list"
            fields:
              - {label: "Icon Image", name: icon_image, widget: image}
              - {label: "Header", name: header, widget: string}
              - {label: "Text", name: text, widget: string}
      - name: "about"
        label: "About"
        file: "src/pages/page-content/about.yml"
        description: "About page content"
        fields:
          - {label: "Intro Blurb", name: "intro_blurb", widget: "string"}
