backend:
  name: github
  repo: mwood23/pride-of-the-meadows

media_folder: static/assets

collections:
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title}
      - { name: data, label: Created At, widget: date }
      - { name: body, label: Post, widget: markdown }
  - name: recipe
    label: Recipes
    folder: src/recipes
    create: true
    fields:
      - { name: title, label: Title}
      - { name: data, label: Created At, widget: date }
      - { name: body, label: Post, widget: markdown }
