- id: Jalapeño Peppers
  tagline: Crisp and Savory
  image: /assets/potm-jalapeno.jpg
  featureOne: Hand-Picked for Quality
  featureTwo: Packed with Flavor
  featureThree: Non-GMO
  productDescription: Originally cultivated in Veracruz, Mexico, these savory chiles have made their way around the world in a variety of dishes. We love to add a dash of chopped jalapeño to nearly every dish for an extra bit of zip.
  recipeName: Jalapeño Poppers
  recipeDate: 24 JUN 2018
  recipeImage: /assets/potm-jalapeno-poppers.jpg
  recipeLink: /recipes/jalapeno-poppers
  recipeDescription: During the summer we love to grill and hang outside. While we're preparing our steaks we fix up a batch of these poppers to tide us over until everything else is ready.
  recipeTag: Recipes
  nutritionFacts: /assets/jalapeno-nutrition-facts.png
- id: Pickles
  tagline: Crisp Pickling Cucumbers
  image: /assets/potm-pickles.jpg
  featureOne: Low-Calorie Snack
  featureTwo: Hand-Picked for Quality
  featureThree: Non-GMO
  productDescription: Not to be confused with their larger sibling, the cucumber, pickles are for more than pickling. Fresh picked pickles make a great snack on the go and have a crispier finish than normal cucumbers.
  recipeName:
  recipeDate:
  recipeImage:
  recipeLink:
  recipeDescription:
  recipeTag: Recipes
  nutritionFacts: /assets/pickles-nutrition-facts.png
- id: Cherry Tomatoes
  tagline: Sweet and Refreshing
  image: /assets/potm-cherry-tomatoes.jpg
  featureOne: Great for Snacking
  featureTwo: Vine-Ripened
  featureThree: Hand-Picked
  productDescription: Containing a sweeter taste and thinner skin than grape tomatoes, they're our go to choice for snacking. Keep them at room temperature for best taste.
  recipeName:
  recipeDate:
  recipeImage:
  recipeLink:
  recipeDescription:
  recipeTag: Recipes
  nutritionFacts: /assets/tom-nutrition-facts.png
- id: Grape Tomatoes
  tagline: Juicy and Fresh
  image: /assets/potm-grape-tomatoes.jpg
  featureOne: Great for Snacking
  featureTwo: Vine-Ripened
  featureThree: Hand-Picked
  productDescription: Often confused with cherry tomatoes, grape tomatoes have a thicker skin making the shelf life longer. They're often used in dishes to provide an extra crunch with a burst of flavor.
  recipeName:
  recipeDate:
  recipeImage:
  recipeLink:
  recipeDescription:
  recipeTag: Recipes
  nutritionFacts: /assets/tom-nutrition-facts.png
- id: Yellow Grape Tomatoes
  tagline: Sweet and Refreshing
  image: /assets/potm-yellow-grape-tomatoes.jpg
  featureOne: Great for Snacking
  featureTwo: Vine-Ripened
  featureThree: Hand-Picked
  productDescription: Don't count these little guys out! Yellow grape tomatoes are often less acidic than their red counterparts and is a great way to add some extra color to a recipe.
  recipeName:
  recipeDate:
  recipeImage:
  recipeLink:
  recipeDescription:
  recipeTag: Recipes
  nutritionFacts: /assets/tom-nutrition-facts.png
