
- id: Jalapeno Peppers
  tagline: crisp and savory
  image: /assets/jalapenos.jpg
  featureOne: Hand-Picked for Quality
  featureTwo: Packed with Flavor
  featureThree: Non-GMO
- id: Pickles
  tagline: crisp and savory
  image: /assets/jalapenos.jpg
  featureOne: Hand-Picked for Quality
  featureTwo: Packed with Flavor
  featureThree: Non-GMO
- id: Cherry Tomatoes
  tagline: crisp and savory
  image: /assets/jalapenos.jpg
  featureOne: Hand-Picked for Quality
  featureTwo: Packed with Flavor
  featureThree: Non-GMO
